//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Webpcon
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> MyDate { get; set; }
        public string Number { get; set; }
        public string Side { get; set; }
        public string System { get; set; }
        public string Module { get; set; }
        public string Project { get; set; }
        public string FProject { get; set; }
        public string AddFunction { get; set; }
        public string elsetext { get; set; }
        public string Description { get; set; }
        public string Fid { get; set; }
        public string Department { get; set; }
        public string Applicant { get; set; }
        public int Status { get; set; }
    }
}
